"""
main.py
=======
CLI Entry point for NavigatorCrew.
Architecture: LangGraph + CrewAI Sequential Pipeline v5.1.
"""

import argparse
import os
import re
import shutil
import subprocess
from datetime import date
from pathlib import Path
from src.config import logger, PROJECT_ROOT

# ---------------------------------------------------------------------------
# Output files produced by agents (relative to PROJECT_ROOT/outputs/)
# ---------------------------------------------------------------------------
_AGENT_OUTPUT_FILES = [
    "paper_outline.md",
    "research_briefs.md",
    "figures_manifest.md",
    "hebrew_prose.md",
    "latex_status.md",
    "quality_report.md",
    "token_report.md",
]


def _topic_slug(topic: str) -> str:
    """Convert topic string to a safe directory slug (max 40 chars)."""
    slug = topic.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug[:40].rstrip("-")


def create_run_folder(topic: str) -> Path:
    """
    Create a uniquely-named run folder under outputs/runs/.

    Naming convention:
        outputs/runs/{topic-slug}-{YYYY-MM-DD}/
        outputs/runs/{topic-slug}-{YYYY-MM-DD}-v2/   (if date already exists)
        outputs/runs/{topic-slug}-{YYYY-MM-DD}-v3/   etc.

    Returns the created Path.
    """
    runs_root = PROJECT_ROOT / "outputs" / "runs"
    runs_root.mkdir(parents=True, exist_ok=True)

    today = date.today().strftime("%Y-%m-%d")
    slug  = _topic_slug(topic)
    base  = f"{slug}-{today}"

    # Find next available version
    candidate = runs_root / base
    version   = 2
    while candidate.exists():
        candidate = runs_root / f"{base}-v{version}"
        version  += 1

    candidate.mkdir(parents=True)
    logger.info(f"[RunFolder] Created: {candidate}")
    return candidate


def archive_run(run_folder: Path, pdf_path: Path | None) -> None:
    """
    Copy all run artifacts into the run folder.

    Layout inside run_folder/:
        outputs/        ← agent .md reports (outline, briefs, quality, tokens, etc.)
        figures/        ← PNG figures generated by VisualizationEngineer (direct access)
        latex/          ← full LaTeX source snapshot (chapters, figures, bib, cls)
        paper.pdf       ← compiled PDF (if available)
        run_manifest.txt ← human-readable index of all archived files
    """
    outputs_src = PROJECT_ROOT / "outputs"
    latex_src   = PROJECT_ROOT / "latex"
    figures_src = latex_src / "figures"

    # 1. Copy agent output .md files
    run_outputs = run_folder / "outputs"
    run_outputs.mkdir(exist_ok=True)
    copied_outputs = []
    for filename in _AGENT_OUTPUT_FILES:
        src = outputs_src / filename
        if src.exists():
            shutil.copy2(src, run_outputs / filename)
            copied_outputs.append(filename)

    # 2. Copy figures directly to top-level figures/ for easy access
    run_figures = run_folder / "figures"
    copied_figures = []
    if figures_src.exists():
        run_figures.mkdir(exist_ok=True)
        for fig in sorted(figures_src.glob("*.png")):
            shutil.copy2(fig, run_figures / fig.name)
            copied_figures.append(fig.name)

    # 3. Copy full LaTeX source snapshot (includes chapters/, figures/, cls, bst)
    run_latex = run_folder / "latex"
    if latex_src.exists():
        shutil.copytree(
            latex_src, run_latex,
            ignore=shutil.ignore_patterns(
                "*.aux", "*.log", "*.toc", "*.out", "*.bbl",
                "*.blg", "*.fdb_latexmk", "*.fls", "*.synctex.gz",
                "main.pdf",
            ),
        )

    # 4. Copy PDF
    if pdf_path and pdf_path.exists():
        shutil.copy2(pdf_path, run_folder / "paper.pdf")

    # 5. Write manifest
    has_pdf = bool(pdf_path and pdf_path.exists())
    manifest_lines = [
        "NavigatorCrew Run Archive",
        "=========================",
        f"Folder  : {run_folder.name}",
        "",
        f"Figures ({len(copied_figures)} PNG files):",
    ]
    for f in copied_figures:
        manifest_lines.append(f"  figures/{f}")
    manifest_lines += [
        "",
        f"Agent outputs ({len(copied_outputs)} files):",
    ]
    for f in copied_outputs:
        manifest_lines.append(f"  outputs/{f}")
    manifest_lines += [
        "",
        "LaTeX source snapshot:",
        "  latex/main.tex",
        "  latex/chapters/   ← all .tex chapter files",
        "  latex/figures/    ← same PNGs as figures/ above",
        "  latex/references.bib",
        "",
        f"PDF: {'paper.pdf' if has_pdf else 'NOT COMPILED (check latex/main.log)'}",
    ]
    (run_folder / "run_manifest.txt").write_text("\n".join(manifest_lines), encoding="utf-8")

    logger.info(
        f"[RunFolder] Archived {len(copied_figures)} figures + "
        f"{len(copied_outputs)} outputs + LaTeX source "
        f"→ {run_folder}"
    )


def compile_pdf() -> Path | None:
    """
    Run the full XeLaTeX → BibTeX → XeLaTeX → XeLaTeX sequence.
    Returns path to the compiled PDF (latex/main.pdf), or None on failure.
    The PDF is copied to the run archive by archive_run(); it is NOT written
    to outputs/ so as to keep that directory clean between runs.
    """
    latex_dir = PROJECT_ROOT / "latex"
    pdf_src   = latex_dir / "main.pdf"

    def run(cmd: list[str]) -> bool:
        result = subprocess.run(
            cmd, cwd=latex_dir,
            capture_output=True, text=True
        )
        if result.returncode != 0:
            logger.warning(f"[LaTeX] {cmd[0]} returned non-zero: {result.stdout[-500:]}")
        return result.returncode == 0

    logger.info("[LaTeX] Compiling PDF (xelatex → bibtex → xelatex × 2)...")
    run(["xelatex", "-interaction=nonstopmode", "main.tex"])
    run(["bibtex", "main"])
    run(["xelatex", "-interaction=nonstopmode", "main.tex"])
    run(["xelatex", "-interaction=nonstopmode", "main.tex"])

    if pdf_src.exists():
        size_mb = pdf_src.stat().st_size / 1_048_576
        logger.success(f"[LaTeX] PDF compiled: {pdf_src} ({size_mb:.1f} MB)")
        return pdf_src
    else:
        logger.error("[LaTeX] PDF compilation failed — check latex/main.log")
        return None


def main():
    _DEFAULT_TOPIC = "Bat-Inspired Drone Navigation via Bio-Mimetic Multi-Modal Sensor Fusion"

    parser = argparse.ArgumentParser(description="NavigatorCrew v5.1")
    parser.add_argument(
        "--topic",
        default=_DEFAULT_TOPIC,
        help=f'Research topic (default: "{_DEFAULT_TOPIC}")',
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from last checkpoint (skips tasks with existing output files)",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Skip PDF compilation after content generation",
    )
    parser.add_argument(
        "--no-archive",
        action="store_true",
        help="Skip archiving outputs to outputs/runs/ (useful for quick smoke tests)",
    )
    args = parser.parse_args()

    logger.info(f"Topic: {args.topic}")
    logger.info(f"Resume Mode: {args.resume}")

    from src.graph.navigator_graph import build_navigator_graph
    from src.graph.state import PipelineState

    logger.info("Building NavigatorCrew LangGraph pipeline...")
    graph = build_navigator_graph()

    initial_state: PipelineState = {
        "topic": args.topic,
        "remediation_count": 0,
        "failed_sections": [],
        "quality_verdict": "PENDING",
        "quality_score": 0,
    }

    try:
        final_state = graph.invoke(initial_state)
    except Exception as e:
        logger.error(f"Graph execution failed: {e}")
        raise

    # ------------------------------------------------------------------
    # PDF Compilation
    # ------------------------------------------------------------------
    pdf_path = None
    if not args.no_pdf:
        pdf_path = compile_pdf()

    # ------------------------------------------------------------------
    # Archive this run to outputs/runs/{slug}-{date}/
    # ------------------------------------------------------------------
    run_folder = None
    if not args.no_archive:
        run_folder = create_run_folder(args.topic)
        archive_run(run_folder, pdf_path)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print("\n" + "=" * 52)
    print("  NAVIGATORCREW — EXECUTION COMPLETE")
    print("=" * 52)
    print(f"  Quality Score    : {final_state['quality_score']}/100")
    print(f"  Verdict          : {final_state['quality_verdict']}")
    print(f"  Remediation Runs : {final_state['remediation_count']}")
    if pdf_path:
        print(f"  Final PDF        : {pdf_path}")
    if run_folder:
        print(f"  Run Archive      : {run_folder}")
    print("=" * 52)


if __name__ == "__main__":
    main()
